#!/bin/bash

# This Shell script runs a Python script specified by the $PYFILE environment variable

# Set the path to the Python script
python_script="0x00-python-hello_world/0-run"

# Check if the Python script exists
if [ -f "$python_script" ]; then
    echo "Running the Python script: $python_script"
    # Run the Python script
    python3 "$python_script"
else
    echo "Error: Python script not found at $python_script"
    exit 1
fi

